IoTWebsiteREST/djangoproject/REST/urls.py
from django.urls import path
from .views import *
from rest_framework.authtoken.views import obtain_auth_token
from allauth.account.views import LoginView, LogoutView

# Se necessario l'id dell'oggetto è contenuto nel json passato, non è presente nell'url

urlpatterns = [
    path('igrometri/', IgrometroAPIView.as_view(), name='igrometro-api'),
    path('igrometri/<int:pk>/', IgrometroAPIView.as_view(), name='igrometro-api-pk'),
    path('igrometri/<int:pk>/misurazioni/', misurazioni, name='misurazioni-api'),
    path('masterigrometri/', MasterIgrometriAPIView.as_view(), name='masterigrometri-api'),
    path('masterigrometri/<int:pk>/', MasterIgrometriAPIView.as_view(), name='masterigrometri-api-pk'),

    path('token/', CustomAuthToken.as_view(), name='token-api'),
]

"""     
    path('igrometri/create/', IgrometroCreateView.as_view(), name='igrometro-create'),
    path('igrometri/<int:pk>/delete/', IgrometroDestroyView.as_view(), name='igrometro-delete'),
    path('igrometri/<int:pk>/update/', IgrometroUpdateView.as_view(), name='update-igrometro'),
 """

""" 
    path('masterigrometri/create/', MasterIgrometriCreateView.as_view(), name='master-create'),
    path('masterigrometri/<int:pk>/delete/', MasterIgrometriDestroyView.as_view(), name='master-delete'),
    path('masterigrometri/<int:pk>/update/', MasterIgrometriUpdateView.as_view(), name='master-update'),
 """

"""
    path('igrometri/aggiungi-ultima-misurazione/', aggiungi_ultima_misurazione, name='aggiungi_ultima_misurazione'),
    path('igrometri/elimina-misurazione/', cancella_ultima_misurazione, name='elimina_misurazione'),
"""

IoTWebsiteREST/djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include ,re_path
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('REST.urls')),
    path('accounts/', include('allauth.urls')),
    path('mqtt/', include('mqtt_integration.urls')),
    path('', include('website.urls')),
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/logo.png')),
    #path('api-auth/', include('rest_framework.urls')),
    #path('api/rest-auth/', include('rest_auth.urls')),
    #path('api/rest-auth/registration/', include('rest_auth.registration.urls')),
]

IoTWebsiteREST/djangoproject/website/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views
from .views import *
app_name = 'website'

urlpatterns = [
    # Altri percorsi e viste possono essere aggiunti qui
    path('lista_master/', lista_master, name='lista_master'),
    path('mappa_aree/', mappa_aree, name='mappa_aree'),
    path('homepage/', homepage, name='homepage'),
    path("logout/", views.custom_logout, name="logout"),
    path('search/', MasterIgrometriSearchView.as_view(), name='search-view'),
    path('update_graph/<int:igrometro_id>/',misurazioni_ajax, name='misurazioni_ajax'),
    path('aggiungi_irrigatore/', AggiungiIrrigatoreView.as_view(), name='aggiungi_irrigatore'),
    path('hygrometer/<int:igrometro_id>/', igrometro_detail_and_edit, name='igrometro_detail_and_edit'),
    path('master/<int:master_id>/', master_detail_and_edit, name='master_detail_and_edit'),
    path('sprinkler/<int:sprinkler_id>/', sprinkler_detail_and_edit, name='sprinkler_detail_and_edit'),
    path('profile/', view_profile, name='view_profile'),
    path('add_sprinkler/', add_sprinkler, name='add_sprinkler'),
    path('about/', about, name='about'),
    path('', homepage, name='homepage2'),
]

IoTWebsiteREST/djangoproject/website/forms.py
# forms.py

from allauth.account.forms import SignupForm
from django import forms
from REST.models import Irrigatore, CustomUser

class IrrigatoreForm(forms.ModelForm):
    class Meta:
        model = Irrigatore
        fields = ['nome', 'latitudine', 'longitudine', 'quota', 'attivo']


class AddIrrigatoreForm(forms.ModelForm):
    class Meta:
        model = Irrigatore
        fields = ['nome', 'latitudine', 'longitudine', 'quota', 'attivo', 'secret']



from django import forms
from REST.models import Igrometro, MasterIgrometri

class IgrometroForm(forms.ModelForm):
    class Meta:
        model = Igrometro
        fields = ['nome', 'latitudine', 'longitudine', 'master']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Remove the default "-------" option for the 'master' field
        self.fields['master'].empty_label = None


class MasterForm(forms.ModelForm):
    class Meta:
        model = MasterIgrometri
        fields = ['nome', 'latitudine', 'longitudine', 'quota']

class SprinklerForm(forms.ModelForm):
    class Meta:
        model = Irrigatore
        fields = ['nome', 'longitudine', 'quota', 'attivo']

class CustomUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'username', 'first_name', 'last_name']

IoTWebsiteREST/djangoproject/website/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import user_passes_test
from django.views import View
from .forms import AddIrrigatoreForm, IgrometroForm, IrrigatoreForm, MasterForm, CustomUserForm
from REST.models import Igrometro, Irrigatore, MasterIgrometri
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

def is_admin(user):
    return user.is_authenticated and user.is_staff


def custom_logout(request):
    logout(request)
    return render(request, 'registration/logout.html')


#@user_passes_test(is_admin)
def lista_master(request):
    masters = MasterIgrometri.objects.all()
    return render(request, 'masters_list.html', {'masters': masters})


def mappa_aree(request):
    return render(request, 'mappa.html', {'sensors': read_and_average()})

def homepage(request):
    return render(request, 'homepage.html', )

def read_and_average():
    # Ottenere tutti i dati degli igrometri
    igrometri = Igrometro.objects.all()

    # Definire le dimensioni del rettangolo
    lat_delta = 0.01
    lon_delta = 0.01

    # Creare una lista per i dati medi dei rettangoli
    rettangoli_dati_medi = []

    # Iterare sugli igrometri
    rettangoli = []
    for igrometro in igrometri:
        # Calcolare i limiti del rettangolo basandosi sulla posizione dell'igrometro
        lat_start = int(igrometro.latitudine / lat_delta) * lat_delta
        lat_end = lat_start + lat_delta
        lon_start = int(igrometro.longitudine / lon_delta) * lon_delta
        lon_end = lon_start + lon_delta

        # Creare il poligono del rettangolo
        rettangolo = {"lat_start": lat_start, "lon_start": lon_start, "lat_end": lat_end, "lon_end": lon_end}
        if rettangolo in rettangoli:
            continue
        else:
            rettangoli.append(rettangolo)

        # Filtrare gli igrometri all'interno del rettangolo
        igrometri_in_rettangolo = igrometri.filter(latitudine__range=(lat_start, lat_end),
                                                   longitudine__range=(lon_start, lon_end))

        if igrometri_in_rettangolo.exists():
            media_valori = sum(i.ultima_misurazione["umidita"] for i in igrometri_in_rettangolo) / len(
                igrometri_in_rettangolo)

            rettangoli_dati_medi.append({
                'latitudine_start': str(lat_start),
                'latitudine_end': str(lat_end),
                'longitudine_start': str(lon_start),
                'longitudine_end': str(lon_end),
                'media_valori': str(media_valori),
            })

    return rettangoli_dati_medi

@method_decorator(login_required, name='dispatch')
class AggiungiIrrigatoreView(View):
    template_name = 'aggiungi_irrigatore.html'

    def get(self, request):
        form = IrrigatoreForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = IrrigatoreForm(request.POST)
        if form.is_valid():
            irrigatore = form.save(commit=False)
            irrigatore.user = request.user  # Associa l'irrigatore all'utente corrente
            irrigatore.save()
            return redirect('website:lista_master')  # Personalizza l'URL di reindirizzamento

        return render(request, self.template_name, {'form': form})


# views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.views import View

from django.http import JsonResponse
from django.views import View


class MasterIgrometriSearchView(View):
    def get(self, request, *args, **kwargs):
        search_name = request.GET.get('searchName', '')
        type = request.GET.get('type', '')
        id = request.GET.get('id', '')


        masters_queryset = MasterIgrometri.objects.all()
        igrometri_queryset = Igrometro.objects.all()
        if id:
            try:
                id = int(id)
                master_instance = MasterIgrometri.objects.get(id=id)
                masters_queryset = [master_instance]
            except (ValueError, MasterIgrometri.DoesNotExist):
                masters_queryset = []
            try:
                id = int(id)
                igrometro_instance = Igrometro.objects.get(id=id)
                igrometri_queryset = [igrometro_instance]
            except (ValueError, MasterIgrometri.DoesNotExist):
                igrometri_queryset = []




        if type == "Master":
            igrometri_queryset = []
            
        elif type == "Hygrometer":
            masters_queryset = []

    
        if search_name:
            masters_queryset = [master for master in masters_queryset if search_name.lower() in master.nome.lower()]
            igrometri_queryset = [igro for igro in igrometri_queryset if search_name.lower() in igro.nome.lower()]

        masters_data = []
        for master in masters_queryset:
            master_data = {
                'id': master.id,
                'nome': master.nome,
                'latitudine': master.latitudine,
                'longitudine': master.longitudine,
                'data_creazione': master.data_creazione,
                'quota': master.quota,
            }
            masters_data.append(master_data)

        igrometri_data = []
        for igrometro in igrometri_queryset:
            igrometro_data = {
                'id': igrometro.id,
                'nome': igrometro.nome,
                'latitudine': igrometro.latitudine,
                'longitudine': igrometro.longitudine,
                'data_creazione': igrometro.data_creazione,
                'ultima_misurazione': igrometro.ultima_misurazione,
                'misurazioni': igrometro.misurazioni,
                'attivo': igrometro.attivo,
                'master_id': igrometro.master_id,
            }
            igrometri_data.append(igrometro_data)

        result_dict = {
            'masters': masters_data,
            'igrometri': igrometri_data
        }
        return JsonResponse(result_dict, safe=False)
    
def igrometro_detail_and_edit(request, igrometro_id):
    if not is_admin(request.user):
        messages.error(request, "You need to be admin in order to get there")
        return HttpResponseRedirect(reverse('website:lista_master'))
    igrometro = get_object_or_404(Igrometro, id=igrometro_id)
    if request.method == 'POST':
        form = IgrometroForm(request.POST, instance=igrometro)
        if form.is_valid():
            form.save()
            return render(request, 'igrometro.html', {'igrometro': igrometro, 'form': form})
    else:
        form = IgrometroForm(instance=igrometro)

    return render(request, 'igrometro.html', {'igrometro': igrometro, 'form': form})


def master_detail_and_edit(request, master_id):
    if not is_admin(request.user):
        messages.error(request, "You need to be admin in order to get there")
        return HttpResponseRedirect(reverse('website:lista_master'))
    master = get_object_or_404(MasterIgrometri, id=master_id)
    igrometri = Igrometro.objects.filter(master=master)
    print(igrometri)
    if request.method == 'POST':
        form = MasterForm(request.POST, instance=master)
        if form.is_valid():
            form.save()
            return render(request, 'master.html', {'master': master, 'form': form , 'igrometri':igrometri})
    else:
        form = MasterForm(instance=master)

    return render(request, 'master.html', {'master': master, 'form': form, 'igrometri':igrometri})

@login_required
def sprinkler_detail_and_edit(request, sprinkler_id):
    irrigatore = get_object_or_404(Irrigatore, id=sprinkler_id)
    if request.method == 'POST':
        form = IrrigatoreForm(request.POST, instance=irrigatore)
        print(form)
        if form.is_valid():
            form.save()
            return render(request, 'irrigatore.html', {'irrigatore': irrigatore, 'form': form})
    else:
        form = IrrigatoreForm(instance=irrigatore) 

    return render(request, 'irrigatore.html', {'irrigatore': irrigatore, 'form': form})


@login_required
def view_profile(request):
    user = request.user
    irrigatori=user.irrigatori.all()
    print(irrigatori)

    if request.method == 'POST':
        form = CustomUserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return render(request, 'profile.html', {'form': form, 'irrigatori':irrigatori })
    else:
        form = CustomUserForm(instance=user)

    return render(request, 'profile.html', {'form': form , 'irrigatori':irrigatori })

@login_required
def add_sprinkler(request):
    if request.method == 'POST':
        form = AddIrrigatoreForm(request.POST)
        if form.is_valid():
            irrigatore = form.save(commit=False)
            irrigatore.user = request.user  # Imposta l'utente corrente come proprietario dell'irrigatore
            irrigatore.save()
            return redirect('website:view_profile')  # Redirect to profile page after adding sprinkler
    else:
        form = AddIrrigatoreForm()
    
    return render(request, 'add_sprinkler.html', {'form': form})




def about(request):
    return render(request, 'about.html')

def misurazioni_ajax(request, igrometro_id):
    igrometro = get_object_or_404(Igrometro, id=igrometro_id)
    return JsonResponse(igrometro.misurazioni, safe=False)

IoTWebsiteREST/djangoproject/website/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About us{% endblock %}
{% block head %}
<style>
        .rounded-img {
      border-radius: 50%;
      max-width: 150px;
      height: auto;
    }
</style>

{% endblock %}
{% block content %}
<div class="container-fluid header bg-white p-0  display-5 animated fadeIn mb-4">
  <img class="img-fluid" src='{% static "img/about2.jpg" %}' alt="">
</div>

<!-- Developers Section -->
<section class="container my-5 animated fadeIn">
    <div class="row flex-row">
      <!-- Developer 3 -->
      <div class="col-lg-4 text-center flex-column">
        <h2 style="color: #0b5966;"> Filippo Bologna</h2>
        <img src='{% static "img/fillo.jpg" %}' alt="Developer 3" class="rounded-img mb-3">
      </div>
      <div class="col-lg-7  flex-column" style="margin-top: 60px; font-size: 20px;">
      <p>
      Bachelor's degree in Computer Engineering, graduated from the University of Modena and Reggio Emilia.<br>
      Master's student in Artificial Intelligence Engineering at the University of Modena and Reggio Emilia.<br>
        <br>
      Took care of the hardware part of the project.
      </p>
    </div>
    </div>
</section>
<section class="container my-5 animated fadeIn" >
  <div class="row flex-row">
    <!-- Developer 3 -->
    <div class="col-lg-4 text-center flex-column">
      <h2 style="color: #0b5966;">Lorenzo Corradi</h2>
      <img src="{% static "img/cordani.jpg" %}" alt="Developer 3" class="rounded-img mb-3">        
    </div>
    <div class="col-lg-7  flex-column" style="margin-top: 60px; font-size: 20px;">
      <p>
        Bachelor's degree in Computer Engineering, graduated from the University of Modena and Reggio Emilia.<br>
        Master's student in Artificial Intelligence Engineering at the University of Modena and Reggio Emilia.<br>
          <br>
        Took care of the front-end part of the project.
      </p>
    </div> 
  </div>
</section>
<section class="container my-5 animated fadeIn">
  <div class="row flex-row">
    <!-- Developer 3 -->
    <div class="col-lg-4 text-center flex-column">
      <h2 style="color: #0b5966;">Marco Morini</h2>
      <img src='{% static "img/foto_profilo.jpg" %}' alt="Developer 3" class="rounded-img mb-3">        
    </div>
    <div class="col-lg-7  flex-column" style="margin-top: 60px; font-size: 20px;">
      <p>
      Bachelor's degree in Computer Engineering, graduated from the University of Modena and Reggio Emilia.<br>
      Master's student in Artificial Intelligence Engineering at the University of Modena and Reggio Emilia.<br>
      Computer Science teacher at Liceo Manfredo Fanti in Carpi.<br><br>
      Took care of the back-end part of the project.
      </p>
    </div>        
  </div>
</section>



{% endblock %}

IoTWebsiteREST/djangoproject/website/templates/aggiungi_irrigatore.html
{% extends "base.html" %}

{% block content %}
  <h2>Aggiungi Irrigatore</h2>
  <form method="post" action="{% url 'website:aggiungi_irrigatore' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Aggiungi</button>
  </form>
{% endblock %}

IoTWebsiteREST/djangoproject/website/templates/mappa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Map with Humidity Data</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <style>
        #map {
            height: 500px;
        }
    </style>
</head>
<body>

<div id="map"></div>

<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
<script src="https://d3js.org/d3.v5.min.js"></script>


<script>
    // Sample sensor data
    const sensorData = {{sensors|safe}};

    // Initialize the map
    const map = L.map('map').setView([45.4642, 9.1900], 13);

    // Add the base map layer
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '© OpenStreetMap contributors'
    }).addTo(map);

    // Set fixed dimensions for the rectangle in kilometers
    const fixedWidthKilometers = 0.01;
    const fixedHeightKilometers = 0.01;

    // Add rectangles to the map based on sensor data
    sensorData.forEach(sensor => {
        const rectangle = L.rectangle([
            [parseFloat(sensor.latitudine_start), parseFloat(sensor.longitudine_start) ],
            [parseFloat(sensor.latitudine_end), parseFloat(sensor.longitudine_end)]
        ], {
            fillColor: getFillColor(sensor.media_valori),
            color: '#000',
            weight: 0,
            opacity: 0,
            fillOpacity: 0.4    
        }).bindPopup(`Humidity: ${sensor.humidity}%`).addTo(map);
    });

    // Function to get fill color based on humidity
// Function to get fill color based on humidity and number of intervals
function getFillColor(humidity) {
    if (humidity <= 10) return '#0ba121'; // Dark Green
    if (humidity <= 20) return '#27d640'; // Green
    if (humidity <= 30) return '#69f57e'; // Light Green
    if (humidity <= 40) return '#90f59f'; // Very Light Green
    if (humidity <= 50) return '#d3f590'; // Light Yellow-Green
    if (humidity <= 60) return '#d4f553'; // Yellow-Green
    if (humidity <= 70) return '#eff553'; // Light Yellow
    if (humidity <= 80) return '#eff553'; // Light Brown
    if (humidity <= 90) return '#6e6014'; // Brown
    return '#695a07'; // Light Brown
}

</script>



</body>
</html>

IoTWebsiteREST/djangoproject/website/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Master e Igrometri sulla Mappa{% endblock %}
{% block head %}
<style>
    /* Stile per la barra di scorrimento */
    .scrollable-container {
        overflow: auto;
        max-height: 300px; /* Imposta un'altezza massima per la visualizzazione della scrollbar */
        border: 0px solid #ccc; /* Opzionale: bordo per migliorare la visualizzazione */
        padding: 10px; /* Opzionale: spazio interno per una migliore presentazione */
    }
    .scrollable-container::-webkit-scrollbar {
            width: 12px;
        }
        .scrollable-container::-webkit-scrollbar-thumb {
            background-color: #1f414d;
            border-radius: 10px;
        }
        .scrollable-container::-webkit-scrollbar-track {
            background-color: #377c85;
            border-radius: 10px;
        }
    table {
            width: 100%;
            border-collapse: collapse;
        }

        table, th, td {
            border: 1px solid #ddd;
        }

        th, td {
            padding: 8px;
            text-align: left;
        }
</style>
<link href='{% static "css/forms.css" %}' rel="stylesheet">'
{% endblock %}
{% block content %}
<div class="container-fluid header bg-white p-0">
            <div class="row g-0 align-items-center flex-column-reverse flex-md-row">
                <div class="col-md-6 p-5 mt-lg-5">
                    <h1 class="display-5 animated fadeIn mb-4">User Profile <span class="text-primary"></span>  </h1>
                    <p class="animated fadeIn mb-4 pb-2">View and edit your profile information, including first and last name. View your sprinklers and add as you wish.</p>
                </div>
                <div class="col-md-6 animated fadeIn">
                    <img class="img-fluid" src='{% static "img/profilo.jpeg" %}' alt="">
 
                    
                </div>
            </div>
        </div>
        <!-- Header End -->


        <div class="container mt-4">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mx-auto" style="padding: 80px;">
                    
        
                    <form method="post">
                        {% csrf_token %}
        
                        <div class="form-row">
                            <div class="form-group col-md-12 mb-3">
                                <label for="{{ form.nome.id }}" style="color: #377c85;">Username:</label>
                                {{ form.username }}
                            </div>
                            <div class="form-group col-md-12 mb-3" style="margin-top: 20px;">
                                <label for="{{ form.longitudine.id }}" style="color: #377c85;">Email:</label>
                                {{ form.email }}
                            </div>
                            <div class="form-group col-md-12 mb-3" >
                                <label for="{{ form.latitudine.id }}" style="color: #377c85;">First name:</label>
                                {{ form.first_name }}
                            </div>
        
                            <div class="form-group col-md-12 mb-3" style="margin-top: 20px;">
                                <label for="{{ form.longitudine.id }}" style="color: #377c85;">Last name:</label>
                                {{ form.last_name }}
                            </div>

                            <div class="form-group col-md-12 mb-7" style="margin-top: 30px;">
                                <button type="submit" class="btn btn-primary">Save Changes</button>
                                
                            </div>
                        </div>
                 
        
                        
                    </form>
  
                </div>
        
                <div class="col-md-6" style="margin-top:59px; color: #1f414d;">
                    <div class="row ">
                        <div class="col-md-6" style=" color: #1f414d;">
                    <h2 style="margin:auto; text-align: center;">Sprinklers:</h2>
                        </div>
                        <div class="col-md-6" style="color: #1f414d;margin-top: 4px;">
                          <button type="button" class="btn btn-primary" style="height: 37px; background-color: #1f414d;" onclick="window.location.href='{% url 'website:add_sprinkler' %}'">Add sprinkler</button>

                        </div>
                    </div>
                    
                    <div class="scrollable-container">
                        <table>
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>ID</th>
                                    <th>Creation Date</th>
                                    <!-- Aggiungi altri attributi secondo necessità -->
                                </tr>
                            </thead>
                            <tbody>
                                {% for irrigatore in irrigatori %}
                                    <tr>
                                        <td><a href="/sprinkler/{{irrigatore.id}}" style="color: #138a6e; text-decoration: none;"> {{ irrigatore.nome }}</a></td>
                                        <td>{{ irrigatore.id }}</td>
                                        <td>{{ irrigatore.data_creazione }}</td>
                                        <!-- Aggiungi altri valori degli attributi secondo necessità -->
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                   
                </div>
            </div>
            
        </div>

        

        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

      
        

        
{% endblock %}