IoTWebsiteREST/djangoproject/REST/urls.py
from django.urls import path
from .views import *
from rest_framework.authtoken.views import obtain_auth_token
from allauth.account.views import LoginView, LogoutView

# Se necessario l'id dell'oggetto è contenuto nel json passato, non è presente nell'url

urlpatterns = [
    path('igrometri/', IgrometroAPIView.as_view(), name='igrometro-api'),
    path('igrometri/<int:pk>/', IgrometroAPIView.as_view(), name='igrometro-api-pk'),
    path('igrometri/<int:pk>/misurazioni/', misurazioni, name='misurazioni-api'),
    path('masterigrometri/', MasterIgrometriAPIView.as_view(), name='masterigrometri-api'),
    path('masterigrometri/<int:pk>/', MasterIgrometriAPIView.as_view(), name='masterigrometri-api-pk'),

    path('token/', CustomAuthToken.as_view(), name='token-api'),
]

"""     
    path('igrometri/create/', IgrometroCreateView.as_view(), name='igrometro-create'),
    path('igrometri/<int:pk>/delete/', IgrometroDestroyView.as_view(), name='igrometro-delete'),
    path('igrometri/<int:pk>/update/', IgrometroUpdateView.as_view(), name='update-igrometro'),
 """

""" 
    path('masterigrometri/create/', MasterIgrometriCreateView.as_view(), name='master-create'),
    path('masterigrometri/<int:pk>/delete/', MasterIgrometriDestroyView.as_view(), name='master-delete'),
    path('masterigrometri/<int:pk>/update/', MasterIgrometriUpdateView.as_view(), name='master-update'),
 """

"""
    path('igrometri/aggiungi-ultima-misurazione/', aggiungi_ultima_misurazione, name='aggiungi_ultima_misurazione'),
    path('igrometri/elimina-misurazione/', cancella_ultima_misurazione, name='elimina_misurazione'),
"""

IoTWebsiteREST/djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include ,re_path
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('REST.urls')),
    path('accounts/', include('allauth.urls')),
    path('mqtt/', include('mqtt_integration.urls')),
    path('', include('website.urls')),
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/logo.png')),
    #path('api-auth/', include('rest_framework.urls')),
    #path('api/rest-auth/', include('rest_auth.urls')),
    #path('api/rest-auth/registration/', include('rest_auth.registration.urls')),
]

IoTWebsiteREST/djangoproject/website/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views
from .views import *
app_name = 'website'

urlpatterns = [
    # Altri percorsi e viste possono essere aggiunti qui
    path('lista_master/', lista_master, name='lista_master'),
    path('mappa_aree/', mappa_aree, name='mappa_aree'),
    path('homepage/', homepage, name='homepage'),
    path("logout/", views.custom_logout, name="logout"),
    path('search/', MasterIgrometriSearchView.as_view(), name='search-view'),
    path('update_graph/<int:igrometro_id>/',misurazioni_ajax, name='misurazioni_ajax'),
    path('aggiungi_irrigatore/', AggiungiIrrigatoreView.as_view(), name='aggiungi_irrigatore'),
    path('hygrometer/<int:igrometro_id>/', igrometro_detail_and_edit, name='igrometro_detail_and_edit'),
    path('master/<int:master_id>/', master_detail_and_edit, name='master_detail_and_edit'),
    path('sprinkler/<int:sprinkler_id>/', sprinkler_detail_and_edit, name='sprinkler_detail_and_edit'),
    path('profile/', view_profile, name='view_profile'),
    path('add_sprinkler/', add_sprinkler, name='add_sprinkler'),
    path('about/', about, name='about'),
    path('', homepage, name='homepage2'),
]

IoTWebsiteREST/djangoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href='{% static "css/animate.min.css" %}' rel="stylesheet">'
    <link href='{% static "css/owl.carousel.min.css" %}' rel="stylesheet">
    <link rel="icon" type="image/png" href="{% static "img/logo.png" %}">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Template Stylesheet -->
    <link href='{% static "css/style2.css" %}' rel="stylesheet">

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src='{% static "js/wow.min.js" %}'></script>
        <script src='{% static "js/easing.min.js" %}'></script>
        <script src='{% static "js/waypoints.min.js" %}'></script>
        <script src='{% static "js/owl.carousel.min.js" %}'></script>
    
        <!-- Template Javascript -->
        <script src='{% static "js/main.js" %}'></script>
        {% block head %} {% endblock %}
</head>
<body>
    <div class="container-xxl bg-white p-0">
    {% block nav %}



        <!-- Navbar Start -->
        <div class="container-fluid nav-bar bg-transparent">
            <nav class="navbar navbar-expand-lg bg-white navbar-light py-0 px-4">
                <a href="{% url 'website:homepage' %}" class="navbar-brand d-flex align-items-center text-center">
                    <div >
                        <img  src='{% static "img/logo.png" %}' alt="Icon" style="width: 60px; height: 60px;">
                    </div>
                    <h1 class="m-0 text-primary">HygroPro</h1>
                </a>
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto">
                        <a href="{% url 'website:homepage' %}" class="nav-item nav-link {% if request.path == '/homepage/' %}active{% endif %}">Home</a>
                        <a href="{% url 'website:lista_master' %}" class="nav-item nav-link {% if request.path == '/lista_master/' %}active{% endif %}">Map</a>
                        
                    
                    

                        
                        <a href="#" class="nav-item nav-link">Contact</a>
                        <a href="{% url 'website:about' %}" class="nav-item nav-link {% if request.path == '/about/' %}active{% endif %}">About us</a>
                        {% if user.is_authenticated %}
                        <a href="{% url 'website:view_profile' %}" class="nav-item nav-link {% if request.path == '/profile/' %}active{% endif %}">Profile</a>
                        {%endif%}
                    </div>

                    
                   {% if user.is_authenticated %}
                    <a href="{% url 'website:logout' %}" class="btn btn-primary px-3 d-none d-lg-flex">Log out</a>
                {% else %}
                    <a href="{% url 'account_login' %}" class="btn btn-primary px-3 d-none d-lg-flex">Log in</a>
                {% endif %}
                </div>
            </nav>
        </div>
        <!-- Navbar End -->
    {% endblock %}

    {% block content %}{% endblock %}


    {% block footer %}
    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col">
                    <h5 class="text-white mb-4">Get In Touch</h5>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>via Brombeis 15, Napoli, Italy</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+039 345 67890</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@HygroPro.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col">
                    <h5 class="text-white mb-4">Quick Links</h5>
                    <a class="btn btn-link text-white-50" href="">About Us</a>
                    <a class="btn btn-link text-white-50" href="">Contact Us</a>
                    <a class="btn btn-link text-white-50" href="">Our Services</a>
                    <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                    <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                </div>
                <div class="col">
                    <h5 class="text-white mb-4">Newsletter</h5>
                    <p>Check news and improvements of our technology</p>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                        <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a class="border-bottom" href="#">HygroPro.com</a>, All Right Reserved. 
                        Designed By Lorenzo Corradi</a>
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <div class="footer-menu">
                            <a href="">Home</a>
                            <a href="">Cookies</a>
                            <a href="">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    <!-- Footer End -->

    {% endblock %}
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
    {% block scripts %}{% endblock %}

    </div>
</body>
</html>